### ISSUE TITLE
Have you considered adding the wrapper to PEAR/Packagist?

### ISSUE THREAD

**Issue by jyc** [matthiasplappert/CloudApp-API-PHP-wrapper#2]
Hello!

First of all, thanks for the useful API. I think that it would be even more easy to use if you registered it at PEAR or [Packagist](http://packagist.org/) - the latter would probably be much more easy.

A Packagist `composer.json` package could be as easy as this:

```
{
    "name": "matthiasplappert/CloudApp-API-PHP-wrapper",
    "require": {
        "php": ">=5.3.0"
    }
}
```

.. which would then allow people to use your library with a `composer.json` like this:

```
{
    "require": {
        "matthiasplappert/CloudApp-API-PHP-wrapper/1.0.0"
    }
}
```

Thanks again for your library, and thanks for reading through this issue.

**Comment by matthiasplappert** [comment]
Just added it to Packagist. Thanks for the suggestion.
